name: Build
run-name: Build - ${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  PROJECT_API_BUILD: './src/proto-api/Milochau.Proto.sln'
  PROJECT_API_TESTS: './src/proto-api/Milochau.Proto.sln'
  DOTNET_VERSION: 7.0.x
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  VERBOSITY: normal

jobs:
  build_iac:
    name: Build (IaC)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and test projects
        uses: amilochau/github-actions/build/terraform@v3

  build_api:
    name: Build (API)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore packages
        shell: pwsh
        run: dotnet restore ${{ env.PROJECT_API_BUILD }} --verbosity ${{ env.VERBOSITY }}
      - name: Build application
        shell: pwsh
        run: dotnet build ${{ env.PROJECT_API_BUILD }} --configuration Release --no-restore --verbosity ${{ env.VERBOSITY }}
      - name: Run tests
        shell: pwsh
        run: dotnet test ${{ env.PROJECT_API_TESTS }} --configuration Release --no-restore --no-build --verbosity ${{ env.VERBOSITY }}
