name: Clean
run-name: Clean - ${{ github.ref }}

on:
  workflow_run:
    workflows:
      - Build
      - Deploy
    types:
      - completed

concurrency: clean

jobs:
  clean:
    name: Clean
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Clean artifacts
        uses: amilochau/github-actions/clean/artifacts@amilochau/clean-artifacts
        with:
          runId: ${{ github.event.workflow_run.id }}
      - name: Log
        shell: pwsh
        run: |
          Write-Output "id: ${{ github.event.workflow_run.id }}"
          ${{ github.event.workflow_run }} | ConvertFrom-Json
          ${{ github.event }} | ConvertFrom-Json
